### ISSUE TITLE
Change Colspan

### ISSUE THREAD

**Issue by rturcios1** [azn8n/Philipino_Food#3]
I think changing the colspan to 1 for Main Dishes will help make sure the beginning of the dishes you list in this column are horizontally inline with the image in your Appetizers section. 

`<td rowspan="1" colspan="1">Appetizers</td>
            <td rowspan ="1" colspan="3">Main Dishes</td>`

**Comment by azn8n** [comment]
I decided not to use tables in my project, but thank you for the feedback!
